### PR TITLE
Load only required locale files

### LINKED ISSUE #2295: Optimize locale string loading
We have 20+ locales now and all Strings from each file are loaded upon first access to the Web UI.  This means 1500+ strings in memory, most of which are unnecessary.  Change the locale loading so that each locale file is only loaded if someone requests that locale.

### PR DESCRIPTION
**Pull request by davydovanton**
Fixed #2295
Also I check `get_locale` web helper with `memory_profiler`. For this I use this code:
``` ruby
MemoryProfiler.report{ 100.times { get_locale } }.pretty_print
```

### Before
```
Total allocated 17626
Total retained 3145

allocated memory by gem
-----------------------------------
   3033634  ruby-2.2.0/lib
     12942  sidekiq
      5040  other
```

### After
```
Total allocated 1220
Total retained 182

allocated memory by gem
-----------------------------------
    143025  ruby-2.2.0/lib
     87608  sidekiq
       240  other
```

gif

### CODE REVIEW

**Comment by mperham** [comment]
There's a bug in your impl: it won't work with several different locales. Write a test to verify you can access both English and Russian strings.

**Comment by davydovanton** [comment]
@mperham I fixed cache for `strings` method and add test case where I send three request with different locales

**Comment by mperham** [comment]
Nicely done!

**Comment by davydovanton** [comment]
thanks for review!  :smile_cat:

**Pull request merged**
