### PR TITLE
Add queue size to web show page

### PR DESCRIPTION
**Pull request by spk**

### CODE REVIEW

**Comment by mperham** [comment]
I don't like the look of it in the page title.  Maybe there's a better design but I'm not a designer so I can't offer an alternative.

**Comment by thegorgon** [comment]
Sorry to pile on, but what if it was like a badge? e.g [bootstrap](https://getbootstrap.com/docs/4.1/components/badge/) or [materialize](https://materializecss.com/badges.html)

**Comment by spk** [comment]
i've updated the PR and screenshot based on @thegorgon suggestion

**Comment by mperham** [comment]
Nice, much better.  `@queue.size` will make a network roundtrip to Redis and be out of sync with the queue pages.  Use `@total_size` instead which suffers from neither problem.

**Comment by bobber205** [comment]
I love this change!

**Comment by spk** [comment]
Thanks @mperham for the fix, cheers

**Pull request merged**
