### PR TITLE
Add process/thread count summary to Busy page

### PR DESCRIPTION
**Pull request by mperham**
Sadly my design skills are minimal so it's not very attractive. CSS help appreciated if anyone wants to polish.

Screen Shot 2021-02-09 at 3 49 51 PM

### CODE REVIEW

**Comment by mperham** [comment]
Here's another option for UI: a new "Cluster Summary" area at the top:

Screen Shot 2021-02-18 at 10 22 19 AM

Yet another option:

Screen Shot 2021-02-18 at 10 32 11 AM

**Comment by mperham** [comment]
Latest

Screen Shot 2021-02-18 at 1 22 55 PM

**Comment by sjahu** [comment]
🎉 latest version using `stats-container`/`stat` looks good!

Another simple approach would be just adding a "total" row to the existing table, since all the stats are derived from it anyway.
image
Totally depends on how prominent you want the summary to be, though; your way's probably better!

**Comment by mperham** [comment]
I thought about that. This change request comes from someone running hundreds of Sidekiq processes so finding the end of that table is actually tough, that’s why I was trying to put this info at the top. 🤷‍♂️

**Comment by sjahu** [comment]
Makes sense 👍

**Comment by mperham** [comment]
I think I will add a sum of RSS as another stat to fill out the row; that might help people detect memory changes.

**Pull request merged**
