### PR TITLE
Add /stats, /stats/queues, & /stats/queues/:name json endpoints to web

### PR DESCRIPTION
**Pull request by moserke**
Fixes issue #2098

### CODE REVIEW

**Comment by mperham** [comment]
Awesome, this is ready to merge.  Can you rebase?

**Comment by moserke** [comment]
Master has been merged back into the branch.

**Comment by seuros** [comment]
@moserke Could you squash your commits ?

**Comment by mperham** [comment]
No need to squash, I'm not that obsessive about git history.

**Comment by mperham** [comment]
Thank you!

**Pull request merged**
