### PR TITLE
Fix incorrect version number within Pro-Changes.md

### PR DESCRIPTION
**Pull request by Geesu**
Just fixes a typo.

### CODE REVIEW

**Comment by davydovanton** [comment]
good catch, thanks for contribution 👍

**Comment by mperham** [comment]
The version is correct. I maintain v2 and v3 branches.

**Comment by davydovanton** [comment]
oh, I'm so sorry 😞

**Comment by davydovanton** [comment]
@mperham if you want, I can reverse this commit

**Comment by mperham** [comment]
Please do. It was correct as is.

**Comment by davydovanton** [comment]
@mperham done. Sorry for hastiness

**Pull request merged**
