### PR TITLE
Use start_with? instead of starts_with? which is only available on Rails

### PR DESCRIPTION
**Pull request by marcelolx**
Just noticed this failing in the sidekiq-scheduler test suite https://github.com/sidekiq-scheduler/sidekiq-scheduler/actions/runs/3399698575/jobs/5653621656#step:5:52

https://github.com/mperham/sidekiq/commit/2bfe30667a6be18a9bdce6415ee5ec3c4bf1a6de

### CODE REVIEW

**Comment by marcelolx** [comment]
not sure why 3.1 is broken 🤔

**Comment by mperham** [comment]
Argh, Matz English strikes again.

**Comment by tisba** [comment]
I think this hasn't been released yet, right? 👀

**Comment by mperham** [comment]
Not yet, I'll prepare 7.0.2 this week. There's a major Enterprise bug which needs a 7.0.2 release too.

**Pull request merged**
