### PR TITLE
Add ability to sort 'Enqueued' page on Web UI by enqueued_at time

### LINKED ISSUE #4041: Add the Ability to Sort Enqueued Page Both By "Most Recently Enqueued" As Well As "Next To Process"
This is a feature request from #4037 

I'd like to have the ability to sort the "enqueued" page so that it shows the jobs either by "Most Recently Enqueued" (as it does now) as well as "Next To Process".

The rationale is that I'd like to be able to sit on the first page (especially with Live Poll enabled) and watch which items are about to be run (among other reasons)

### PR DESCRIPTION
**Pull request by fatkodima**
Screen Shot 2019-09-08 at 02 13 47
Also closes #4041

### CODE REVIEW

**Comment by mperham** [comment]
you aren’t sorting based on enqueued_at but just list index. Should the UI reflect that? Otherwise I see it as a potential source of support issues and bug reports.

**Comment by fatkodima** [comment]
Ah, yes, it is just listing queue in head-tail and tail-head order, wrong column name.

> Should the UI reflect that?

You mean changing column name or something else?

**Comment by fatkodima** [comment]
Updated. Please, review.
Screen Shot 2019-09-08 at 16 40 53

**Comment by mperham** [comment]
Instead of "Position", use "#" which is language independent.

**Comment by fatkodima** [comment]
@mperham Done. Anything else?

**Comment by mperham** [comment]
thank you!

**Pull request merged**
