### PR TITLE
Clarify relationship with Rails

### PR DESCRIPTION
**Pull request by adamniedzielski**
Closes https://github.com/mperham/sidekiq/issues/5213.

/cc @dpep @erchn

My personal opinion is that the current version is clear, but if it confused somebody why not make it clearer?

### CODE REVIEW

**Comment by adamniedzielski** [comment]
@mperham you closed this PR without any comment. This makes me feel disheartened. I need to get more positive feedback from you. Could you either be more verbose in your communication or state clearly that you welcome individual contributions, but you're not interested in having me helping out with the overall maintenance of Sidekiq?

**Comment by mperham** [comment]
Yeah, sorry about that. The original reporter closed the issue and I think the text is fine as is.

**Comment by mperham** [comment]
I really do appreciate your help, you've been great responding to issues and helping others. Help is always welcome but as you point out, I can do a better job communicating with and respecting the efforts of others.

**Comment by adamniedzielski** [comment]
Thank you 🤗

**Pull request closed without merging**
