### PR TITLE
dir should from options[:require], rails.root maybe only for developm…

### PR DESCRIPTION
**Pull request by houdl**
dir should from options[:require], rails.root maybe only for development use

### CODE REVIEW

**Comment by mperham** [comment]
Why?

**Comment by houdl** [comment]
@mperham   when i only use grape framework, there is no anything about rails.

**Comment by mperham** [comment]
`default_tag` is only called if Rails is detected.  You can set your tag with `-g xyz`.

**Comment by houdl** [comment]
ok, thanks

**Comment by houdl** [comment]
@mperham   i think that it should have a default tag even if it is not used in rails framwork.

**Comment by mperham** [comment]
How?  What should it be?

**Comment by houdl** [comment]
@mperham  bacause we always not set tag for sidekiq a lot of time.  in capistrano-sidekiq , the tag also is nil , so when we not use rails, there alway have a error message, something like 
```ruby
no implicit conversion of nil into String
sidekiq/cli.rb:257:in `basename'
```
i think sidekiq should have a default tag not only for rails.

**Comment by mperham** [comment]
The only time it calls `default_tag` is when options[:require] is a directory, which is what happens when you don't give Sidekiq a boot script for your application, e.g. `-r ./boot.rb`.  Sidekiq assumes Rails in that case because that is what 90% of people are using.  Use `-r` so Sidekiq knows how to boot your non-Rails app.

**Comment by houdl** [comment]
@mperham  thanks for your answer patiently. i have know what your mean. options[:require] directory only for rails, other framwork must appoint enviroment file.

**Pull request closed without merging**
