### PR TITLE
Make Sidekiq Web UI RTL-friendly

### PR DESCRIPTION
**Pull request by mperham**
Arabic, Hebrew, Farsi and Urdu are all RTL (right-to-left) languages.  Building a webapp that can work in both LTR and RTL is a challenge but can be done.  Let's research and determine if it's feasible to do this without a major redesign.  Some interesting resources:

https://hacks.mozilla.org/2015/09/building-rtl-aware-web-apps-and-websites-part-1/
https://hacks.mozilla.org/2015/10/building-rtl-aware-web-apps-websites-part-2/
https://github.com/morteza/bootstrap-rtl

### CODE REVIEW

**Comment by mperham** [comment]
Ready for review and/or visual feedback.

**Comment by mperham** [comment]
Why the Hebrew placeholder?

**Comment by mperham** [comment]
I like the TextDirection hack.  Good idea!

**Comment by mperham** [comment]
What is the iw locale?

**Comment by seuros** [comment]
iw is for hebrew. I want someone to contribute to it.

**Comment by mperham** [comment]
Hebrew's code is he.

**Comment by seuros** [comment]
My bad. I will fix it now

**Pull request merged**
