### PR TITLE
Update application.css

### PR DESCRIPTION
**Pull request by x235**
移除googlefonts引用，天朝政府我艹尼玛

### CODE REVIEW

**Comment by aprescott** [comment]
Instead of removing these fonts altogether, perhaps they could be downloaded and stored locally?

**Comment by mperham** [comment]
#2144 I thought we had already removed Google fonts for Chinese users?

**Comment by aprescott** [comment]
Oh, weird. They're not in `master`. I have no idea why git/github would show a diff for this commit...

**Comment by mperham** [comment]
It's not in master: https://github.com/mperham/sidekiq/blob/master/web/assets/stylesheets/application.css

We do need to remove the Google font names from font-face.

**Comment by mperham** [comment]
@x235 I think you need to pull the latest master.  This was removed in 3.3.1.

**Pull request closed without merging**
