### PR TITLE
Handle circular error causes

### LINKED ISSUE #2284: Stack level too deep by circular error causes
#### Description
When having Errors with circular causes, Sidekiq performs an infinite recursion. In some cases you want to handle your errors in a way that creates those circular causes. You can see the ruby and sidekiq versions in the sidekiq output below. The Rails version is in the section "Execution".

```
❯ redis-cli --version
redis-cli 2.8.19
```

#### Code
```ruby
class ErrorsDemoWorker
  include Sidekiq::Worker

  def perform
    ErrorsDemo.new.call
  end
end
```

```ruby
class ErrorsDemo
  class OriginalError < ::StandardError; end
  class OurError < ::StandardError; end
  class NotOurError < ::StandardError; end

  def call
    call_working_method
  rescue NotOurError => e
    raise e.cause
  end

  def call_working_method
    do_some_work
  rescue OriginalError => e
    if our_error?(e)
      raise OurError, 'please handle this'
    else
      raise NotOurError, 'just propagate this'
    end
  end

  def do_some_work
    raise OriginalError, 'this is not our error'
  end

  def our_error?(error)
    error.message == 'this is our error'
  end

  def call_and_rescue
    call
  rescue => e
    e.object_id == e.cause.cause.object_id
  end
end
```

#### Execution
```
❯ rails c
Loading development environment (Rails 4.1.1)
irb(main):001:0> ErrorsDemo.new.call_and_rescue
=> true
irb(main):002:0> ErrorsDemoWorker.perform_async
=> "25ae512b1b97d2b0d6034057"
```

#### Sidekiq output with the error
```
2015-04-03T06:08:42.609Z 10424 TID-oxm0g39as INFO: Running in ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14]
2015-04-03T06:08:42.609Z 10424 TID-oxm0g39as INFO: See LICENSE and the LGPL-3.0 for licensing details.
2015-04-03T06:08:42.609Z 10424 TID-oxm0g39as INFO: Upgrade to Sidekiq Pro for more features and support: http://sidekiq.org/pro
2015-04-03T06:08:42.609Z 10424 TID-oxm0g39as INFO: Starting processing, hit Ctrl-C to stop
2015-04-03T06:08:42.638Z 10424 TID-oxm0jh85w INFO: Booting Sidekiq 3.3.2 with redis options {}
2015-04-03T06:08:56.179Z 10424 TID-oxm13nvmg ErrorsDemoWorker JID-25ae512b1b97d2b0d6034057 INFO: start
2015-04-03T06:08:56.180Z 10424 TID-oxm13nvmg ErrorsDemoWorker JID-25ae512b1b97d2b0d6034057 INFO: fail: 0.001 sec
2015-04-03T06:08:56.181Z 10424 TID-oxm13nvmg WARN: {"retry"=>true, "queue"=>"default", "class"=>"ErrorsDemoWorker", "args"=>[], "jid"=>"25ae512b1b97d2b0d6034057", "enqueued_at"=>1428041336.175657}
2015-04-03T06:08:56.181Z 10424 TID-oxm13nvmg WARN: stack level too deep
2015-04-03T06:08:56.182Z 10424 TID-oxm13nvmg WARN: /usr/local/opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sidekiq-3.3.2/lib/sidekiq/middleware/server/retry_jobs.rb:193:in `exception_caused_by_shutdown?'
/usr/local/opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sidekiq-3.3.2/lib/sidekiq/middleware/server/retry_jobs.rb:196:in `exception_caused_by_shutdown?'
<1144 times the same line in the stack trace>
/usr/local/opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sidekiq-3.3.2/lib/sidekiq/middleware/server/retry_jobs.rb:196:in `exception_caused_by_shutdown?'
/usr/local/opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sidekiq-3.3.2/lib/sidekiq/middleware/server/retry_jobs.rb:80:in `rescue in call'
/usr/local/opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sidekiq-3.3.2/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
/usr/local/opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sidekiq-3.3.2/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/usr/local/opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sidekiq-3.3.2/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
/usr/local/opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sidekiq-3.3.2/lib/sidekiq/logging.rb:24:in `with_context'
/usr/local/opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sidekiq-3.3.2/lib/sidekiq/middleware/server/logging.rb:7:in `call'
/usr/local/opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sidekiq-3.3.2/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/usr/local/opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sidekiq-3.3.2/lib/sidekiq/middleware/chain.rb:132:in `call'
/usr/local/opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sidekiq-3.3.2/lib/sidekiq/middleware/chain.rb:132:in `invoke'
/usr/local/opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sidekiq-3.3.2/lib/sidekiq/processor.rb:51:in `block in process'
/usr/local/opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sidekiq-3.3.2/lib/sidekiq/processor.rb:98:in `stats'
/usr/local/opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sidekiq-3.3.2/lib/sidekiq/processor.rb:50:in `process'
/usr/local/opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
/usr/local/opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
/usr/local/opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:122:in `dispatch'
/usr/local/opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
/usr/local/opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
/usr/local/opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
/usr/local/opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
/usr/local/opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
```

#### Suggestion
In [master/lib/sidekiq/middleware/server/retry_jobs.rb](https://github.com/mperham/sidekiq/blob/be7d77d9eddc2fdd818ef7bd4c31b6e897c93859/lib/sidekiq/middleware/server/retry_jobs.rb#L191-197), add an array of already checked `object_id`s to the method `exception_caused_by_shutdown?` and only call itself if the `cause.object_id` is not yet in the array:

```ruby
        def exception_caused_by_shutdown?(e, checked_causes = [])
          # In Ruby 2.1.0 only, check if exception is a result of shutdown.
          return false unless defined?(e.cause)

          # Handle circular causes
          checked_causes << e.object_id
          return false if checked_causes.include?(e.cause.object_id)

          e.cause.instance_of?(Sidekiq::Shutdown) ||
            exception_caused_by_shutdown?(e.cause, checked_causes)
        end
```

### PR DESCRIPTION
**Pull request by eugenk**
Shall fix #2284. While checking whether an application error or a
sidekiq shutdown caused the exception, we keep track of the causes that
were already checked. If a cause was already checked, we can stop
because the whole transitive closure of its causes was checked as well.

### CODE REVIEW

**Comment by seuros** [comment]
LGTM.
Can you add a test please ?

**Comment by eugenk** [comment]
Sure, but it will probably take until Tuesday, because I don't have much time now.

**Comment by eugenk** [comment]
I just added the test. It only tests the private method `exception_caused_by_shutdown?`. I hope this is okay with you.

**Comment by mperham** [comment]
You also need to exercise the base case: a normal exception with no cause.

**Comment by eugenk** [comment]
Yes, you're right. I just added this.

**Comment by seuros** [comment]
Awesome !

**Pull request merged**
