### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by adisos**

### CODE REVIEW

**Comment by davydovanton** [comment]
cool! :shipit:

**Comment by mperham** [comment]
Merge it. You're a committer. :-)

**Comment by davydovanton** [comment]
okay :)
_P.S.: @adisos please, in future, add `[skip ci]` text to commit message for doc and locale changes_

**Comment by adisos** [comment]
okay =)

**Comment by davydovanton** [comment]
@adisos thanks :+1:

**Pull request merged**
