### PR TITLE
Add Arabic translation for Web UI

### PR DESCRIPTION
**Pull request by davydovanton**
Thanks to my friend (_Milena Novakova_) which helped me to create this locale file :blush:

### CODE REVIEW

**Comment by seuros** [comment]
It don't make sense to add Arabic to the locales without an RTL layout, also some words used are not the technical ones.
_˙ʎɐʍ pɹᴉǝʍ ɐ uᴉ ǝʇᴉɹʍ/pɐǝɹ ǝM_

Thank Milena Novakova for your contribution.

**Comment by davydovanton** [comment]
so, may be you're right. Thanks for catch @seuros

**Comment by seuros** [comment]
@davydovanton can we reopen this PR ?

**Comment by davydovanton** [comment]
I think yes

**Pull request closed without merging**
