### PR TITLE
Prefer warn over puts so these can be suppressed

### PR DESCRIPTION
**Pull request by qrush**
So we're using `Sidekiq::Testing.inline!` for some interesting things @wistia - I'd love to be able to suppress the `puts` statements since we now require this file in development + staging environments. 🙏🏼

### CODE REVIEW

**Comment by mperham** [comment]
Long time, Nick, welcome!

whaddya think about adding these keywords that can act as more context?

https://ruby-doc.org/core-3.0.1/Kernel.html#method-i-warn

**Comment by qrush** [comment]
@mperham it's been too long 😁 

Which `uplevel` would you prefer?

**Comment by mperham** [comment]
Whatever prints the best output for your usage. What's reasonable?

**Comment by qrush** [comment]
`uplevel: 1` sounds good to me - the only example I can find in my bundle is via rexml:

https://github.com/ruby/rexml/blob/e941ff17ed3dad428d946b15524bb3529e684266/lib/rexml/cdata.rb#L60-L62

**Comment by mperham** [comment]
In Ruby 3.0 I think you can silence warnings by category. What category? :sidekiq? :sidekiq_testing?

**Comment by mperham** [comment]
I’m trying to figure out what the semantics of category are. It’s different from what I thought. Looks like there’s only two categories: deprecated and experimental. Neither fits this use.

https://bugs.ruby-lang.org/issues/17122

**Comment by qrush** [comment]
Looks that way to me. We are still on 6.0 so need to spend a bit more time to get up to this patch- almost there!

**Comment by mperham** [comment]
Also, I think we should remove the lines of stars. It's unnecessary output.

**Comment by qrush** [comment]
Thanks @mperham !!

**Comment by mperham** [comment]
Thanks for putting up with my comments. I love a gleaming, highly polished bike shed.

**Pull request merged**
