### PR TITLE
Fix charts position on dashbord page [web UI]

### PR DESCRIPTION
**Pull request by davydovanton**
### Before:
screenshot 2015-03-25 01 45 53

### After:
screenshot 2015-03-25 01 45 40

### CODE REVIEW

**Comment by mperham** [comment]
Can you confirm it looks good in desktop, tablet and mobile widths?

**Comment by davydovanton** [comment]
yes, of course.

### Desktop
screenshot 2015-03-25 01 59 18

### Tablet
screenshot 2015-03-25 01 56 11

### Mobile
screenshot 2015-03-25 01 56 22

### Iphone 6 screen :smile: 
screenshot 2015-03-25 02 00 48

**Comment by seuros** [comment]
Thank you :+1:

**Comment by mperham** [comment]
Fantastic!

**Comment by davydovanton** [comment]
Thanks for review :tada:

**Pull request merged**
