### PR TITLE
Add api documentation

### PR DESCRIPTION
**Pull request by SamArdrey**
Add Rdoc documentation

- [ ] Install yard
- [ ] Document everything in .api file
- [ ] Add ignores to everything not in .api file

### CODE REVIEW

**Comment by mperham** [comment]
I'm not sure how to push my changes to your repo, ugh!

**Comment by SamArdrey** [comment]
hahaha

**Comment by SamArdrey** [comment]
it's already checked

**Comment by mperham** [comment]
Change in plans, I'll just give you commit bit here. Only rule is that you always work in your own branches, don't touch main. I'll commit what we have here and you can start a new branch for further rdoc work.

**Comment by SamArdrey** [comment]
Copy

**Pull request merged**
