### PR TITLE
Display Process index number (provided by -i option) on Web UI

### LINKED ISSUE #2410: Display Process' index number (i.e. the number provided by -i option) on Web UI
Would be nice to know which processes might conflict with each other if the UI displayed the index and hostname next to the process name?

### PR DESCRIPTION
**Pull request by gaurish**
Fixes #2410

### CODE REVIEW

**Comment by davydovanton** [comment]
:+1:
@mperham what do you think? Can I merge this changes?

**Comment by mperham** [comment]
Hold off please, I want to think about what to do here.

**Comment by seuros** [comment]
I think we should implement just a hook here.

**Comment by mperham** [comment]
You can already add the index as a tag and it will display in the UI.

**Comment by gaurish** [comment]
^^in that case that we add the following line at the end of `reliable_fetch.rb` in sidekiq-pro

```
Array(Sidekiq.options[:labels]) << Sidekiq.options[:index]
```

**Comment by mperham** [comment]
That is what I recommend.  Don't edit any gem source code, add it to your initializer:

```ruby
Sidekiq.configure_server do |config|
  Array(Sidekiq.options[:labels]) << Sidekiq.options[:index]
end
```

**Pull request closed without merging**
