### PR TITLE
Dump the context as JSON for proper logging

### PR DESCRIPTION
**Pull request by aiionx**
Dump the context as JSON for proper logging

### CODE REVIEW

**Comment by mperham** [comment]
What problem are you trying to solve?

**Comment by aiionx** [comment]
Hi.

The Log prints the context as a ruby structure:
```
2016-04-15T02:45:00.240Z 9316 TID-osw3ap2is WARN: {"class"=>"ProjectWebHookWorker", "args"=>[...], "retry"=>true, "queue"=>"project_web_hook", "jid"=>"64f5e0416015381122462373", "created_at"=>1460671848.3572097, "enqueued_at"=>1460688290.1475492, "error_message"=>"Net::ReadTimeout", "error_class"=>"Net::ReadTimeout", "failed_at"=>1460671867.5247047, "retry_count"=>10, "retried_at"=>1460688300.2396612}
```

Its better if is printed as JSON

```
2016-04-15T02:45:00.240Z 9316 TID-osw3ap2is WARN: {"class": "ProjectWebHookWorker", ...}
```

That way it can be easily parsed.

Sorry I pushed without testing in local env.
If this is approved I can fix, otherwise it can be dropped

**Comment by mperham** [comment]
It's not really designed for parsing, just reading by a developer.  Ideally you have another error handler which is pushing errors to an error service, like Honeybadger, Bugsnag, etc.  That said, I don't have a problem with your change, presuming you fix it.

**Comment by aiionx** [comment]
Thanks,

I'm parsing your logs with logstash.
It makes it easier if the output is JSON and not a raw ruby data structure.

Test passes.

**Pull request merged**
