### PR TITLE
Add keyword arguments support in extensions

### PR DESCRIPTION
**Pull request by 4e4c52**
This PR allows the delay extension to support keyword arguments.
I know the extensions will be deleted in 7.0 but it would be a nice addition in the meantime.

### CODE REVIEW

**Comment by mperham** [comment]
Nice, good catch.

There doesn't appear to be a test for the actual perform call, asserting that any kwargs are filled in as expected.

**Comment by 4e4c52** [comment]
@mperham I added more test to check the keyword arguments forwarding 😉

**Comment by 4e4c52** [comment]
I added a condition to check if the kwargs are empty so I do not pass them to the proxied object.
Looks like it has to do with what's described here: https://eregon.me/blog/2021/02/13/correct-delegation-in-ruby-2-27-3.html

**Comment by mperham** [comment]
Thank you!

**Comment by mperham** [comment]
I reverted this support. It was becoming a maintenance chore; they will be removed soon and I don't have any desire to increase their maintenance burden in the meantime.

**Pull request merged**
