### PR TITLE
adds pronunciation instruction to README

### PR DESCRIPTION
**Pull request by jasonfb**

### CODE REVIEW

**Comment by mperham** [comment]
Thanks, it is true but I don't think it's README-worthy.

**Comment by jasonfb** [comment]
Your call, all I can tell you is I've met a few devs who mis-pronounce it. also confusing because it ends in a "q" with no following "u" so it breaks normal rules of English. nonetheless thanks for the consideration! 👍

**Comment by jasonfb** [comment]
some pronounce it "sidequeue"

**Comment by vassilevsky** [comment]
[ciderkik] is also a thing

**Pull request closed without merging**
