### PR TITLE
Refactor session store using enumerable

### PR DESCRIPTION
**Pull request by davydovanton**
```
2.2.2 :005 > {a: 1, b: 2, c: 3}.each_with_object({}) { |(key, value), hash| hash[key.to_s] = value }
=> {"a"=>1, "b"=>2, "c"=>3}
```

### CODE REVIEW

**Comment by mperham** [comment]
:-1: I want the monkeypatch to be as close to the original code as possible.

https://github.com/rack/rack/blob/master/lib/rack/session/abstract/id.rb#L149

**Comment by davydovanton** [comment]
I understand, thanks.
So, I need to push PR to rack :trollface:

**Comment by mperham** [comment]
Go for it.  If you could push the session fix to Rails too, that would be great.  :laughing:

**Comment by davydovanton** [comment]
nop, `stringify_keys` with `#each` is most fast implementation. :sweat: 
If you're interested I can show benchmarks.

And what bug with session you have? :hushed:

**Comment by mperham** [comment]
See #2460

**Pull request closed without merging**
