### PR TITLE
lazy loading the redis pool 

### PR DESCRIPTION
**Pull request by TiagoCardoso1983**
Related with https://github.com/mperham/sidekiq/issues/2755

This bypasses redis pool creation until it is needed. It's a minor improvement for the normal usage of sidekiq, but improves CoW support when switching to server mode after fork. 

This is however not enough in the standard case due to the configure_client and configure_server blocks which will usually be called before fork (if one wants to eager load a rails app before forking, for example), if one wants to define different error handlers and other stuff you may do in your configure blocks (although one could take the same approach as in middlewares where one defines them separately).  

This is not related to the swarm feature from enterprise mode, instead it's for the use case of preloading a rails app in a master process, fork it and initialize sidekiq server.

### CODE REVIEW

**Comment by mperham** [comment]
Sorry, not a chance I'm putting a mutex there. You'll need to monkey patch.

**Comment by TiagoCardoso1983** [comment]
Understand your concern. Just gonna say that the mutex block part will be run at-most-once, after which you'll no longer need to go through it to access the redis variable. I'm already monkey-patching.

**Comment by mikegee** [comment]
@mperham Could you add a word about why a mutex is bad there for causal issue readers like me? Is it because that is a frequently executed method that you don't want to add overhead to?

**Comment by mperham** [comment]
@mikegee In this case I was mostly concerned about readability.  I already have a plan for building similar functionality which doesn't require hacking those core methods.

I was concerned about a Mutex in a performance critical method but he's right that his double checked locking mostly fixes that issue.

**Comment by mikegee** [comment]
Thank you!

**Pull request closed without merging**
