### PR TITLE
Dynamically update UTC time in footer

### PR DESCRIPTION
**Pull request by davydovanton**

### CODE REVIEW

**Comment by mperham** [comment]
I like the fact that the time in the footer reflects when the data in the page was rendered.

**Comment by newdark** [comment]
:+1: This would be nice to have.

**Comment by mperham** [comment]
@newdark if you turn on polling, the footer will update every two seconds.  The time is meant to represent when the page was rendered so you know how old the data is.

Sidekiq uses UTC everywhere (e.g. log output).  I don't want to show timezone-specific times in one place but not others.

**Comment by newdark** [comment]
Ok that adds up. I can see how you would not want that considering it can be confusing. I just thought I might be helpful to show the user time zone. But that is much larger amount of work so I get you.

**Comment by davydovanton** [comment]
Mike, what advantage in displaying the time when the page was loaded?

**Comment by aprescott** [comment]
Knowing what the state of things like the retry queue was at a particular timestamp is useful in certain cases when you're debugging. By comparison, I don't need the current time on Sidekiq's UI. I have a clock for that. :)

**Comment by davydovanton** [comment]
So, Mike, think I will close this PR, okay?

**Comment by mperham** [comment]
Oh yes, sorry, I was on mobile for the discussion so I couldn't close it myself.  Thanks for starting the discussion.

**Comment by davydovanton** [comment]
No problems :)
Thanks for feedback

**Pull request closed without merging**
