### PR TITLE
Adaptive mobile tables

### PR DESCRIPTION
**Pull request by davydovanton**
#2290 issue

Now it looks like this
screenshot 2015-04-09 02 14 55
screenshot 2015-04-09 02 15 05
screenshot 2015-04-09 23 35 01

### CODE REVIEW

**Comment by davydovanton** [comment]
@mperham, @seuros I completed this PR, what do you think?

**Comment by mperham** [comment]
I'm :-1: on it.  It dramatically increases the length of the page.  Yeah, with the current styling if you're on a thin screen you'll need to scroll right but I don't think of that as a "bug".

**Comment by dmitry** [comment]
Isn't it better to make it optional (for example, through the `client_middleware`)?

**Comment by davydovanton** [comment]
@mperham what do you think about @dmitry idea?

**Comment by w-A-L-L-e** [comment]
Nice job!

**Comment by davydovanton** [comment]
Mike, what will we doing with this changes? If you don't like these changes we can close this PR

**Comment by dmitry** [comment]
Hopefully it will be merged. :+1:

**Comment by mperham** [comment]
I prefer the wide tables.  Denser and less scrolling.

**Pull request closed without merging**
