### PR TITLE
Create table containers with overflow is overlay

### LINKED ISSUE #2290: Update tables for mobile screen
Hello all :v:
I have the idea to update the table layouts, so that they are more adaptive. For example long tables for mobile screen looks like this:
screenshot 2015-04-07 00 00 12
screenshot 2015-04-07 00 00 22

But I want that they looks like this:
screenshot 2015-04-06 23 57 46
screenshot 2015-04-06 23 57 54

What do you think?

### PR DESCRIPTION
**Pull request by davydovanton**
Fix #2290 

sidekiq-tables

### CODE REVIEW

**Comment by mperham** [comment]
What do you think about creating a table helper method to generate the div and table tags?

**Comment by davydovanton** [comment]
So, idea is great but i have a problem with `capture`. Because I use simple version based on [sinatra contrib](https://github.com/sinatra/sinatra-contrib/blob/master/lib/sinatra/capture.rb). The problem is that this `capture` method not work with `<%= ... %>` well. You can check this on [documentation](https://github.com/sinatra/sinatra-contrib/blob/master/lib/sinatra/capture.rb#L43-L47). Because that, I can create helper, but it will be look like as this:

``` erb
<% table = table do %>
  <h3><%= t('Processes') %></h3>
<% end %>
<%= table %>
```

I think that it's ugly, but anyway, what do you think?

**Comment by mperham** [comment]
Yeah, that's not worth it.

**Comment by davydovanton** [comment]
:metal:

**Pull request merged**
