### PR TITLE
Update table layout on index page

### LINKED ISSUE #2735: Website looks terrible on iPhone
It's pretty bad. Not sure if it's just iPhone or all mobile. http://sidekiq.org

### PR DESCRIPTION
**Pull request by davydovanton**
Fixed #2735

#### Gif
keosmrvdty

### P.S.
I didn't check this layout on windows, linux and android. If you can - do it please.

### CODE REVIEW

**Comment by seuros** [comment]
Let me check!

**Comment by davydovanton** [comment]
@seuros it will be really cool if you check it in windows and linux desktop. I checked it on android phone and it work correct :tada:

**Comment by seuros** [comment]
Checked ! :+1:

**Comment by seuros** [comment]
Thank you.

**Comment by davydovanton** [comment]
Thanks for check!

**Pull request merged**
