### PR TITLE
Warn if client concurrency cannot be determined

### PR DESCRIPTION
**Pull request by DylanReile**
Hi there!

We ran into a problem where our Puma processes had 20+ threads sharing the default pool of 5 Redis connections. This would occasionally throw confounding `ConnectionPool::Timeout` errors as the threads competed for a pool that was too shallow.

Unfortunately we were using `ENV['PUMA_MAX_THREADS']` instead of `ENV['RAILS_MAX_THREADS']` to set our thread count. Had we been using the latter, the pool would have been right-sized for us automatically.

I've added this warning as it would have helped us debug. Throwing an error—`Web concurrency cannot be determined. Please set RAILS_MAX_THREADS`—would have helped us catch it even before it hit production, but I don't want to break anything here.

### CODE REVIEW

**Comment by mperham** [comment]
I don't want to make this environment variable mandatory. IME it's unusual to require so many client connections and there are benefits (esp in environments where Redis connections are tightly limited) to keeping the pool size smaller than thread count.

**Comment by DylanReile** [comment]
@mperham Agreed, I'm actually trying to convince my team to reduce to 5 threads. Just wondering, since this size is a max and the connections are lazily created, wouldn't they only be created if they really were needed? What triggers that?

**Comment by mperham** [comment]
Right. 10 threads is the default, you might just stick to that. Sharing 5
connections across 10 threads seems very reasonable. The connection_pool
gem does the connection mgmt.

**Comment by DylanReile** [comment]
@mperham Are you talking about the Puma default thread count?

**Pull request closed without merging**
