### PR TITLE
Require extensions in lib/testing.rb

### LINKED ISSUE #4300: Fail `require 'sidekiq/testing'` on `master` blanch
Ruby version: 2.6.4
Sidekiq / Pro / Enterprise version(s): `master` branch

```
$ git clone git@github.com:mperham/sidekiq.git
$ cd sidekiq
$ irb
irb(main):001:0> require './lib/sidekiq/testing'
Traceback (most recent call last):
        8: from /Users/tnakata/.rbenv/versions/2.6.4/bin/irb:23:in `<main>'
        7: from /Users/tnakata/.rbenv/versions/2.6.4/bin/irb:23:in `load'
        6: from /Users/tnakata/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
        5: from (irb):1
        4: from /Users/tnakata/.rbenv/versions/2.6.4/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        3: from /Users/tnakata/.rbenv/versions/2.6.4/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        2: from /Users/tnakata/workspace/sidekiq/lib/sidekiq/testing.rb:6:in `<top (required)>'
        1: from /Users/tnakata/workspace/sidekiq/lib/sidekiq/testing.rb:336:in `<module:Sidekiq>'
NameError (uninitialized constant Sidekiq::Extensions::DelayedMailer)
irb(main):002:0> exit

$ git checkout refs/tags/v6.0.0
...
$ irb
irb(main):001:0> require './lib/sidekiq/testing'
=> true
```

Looks like it needs `require "sidekiq/extensions/action_mailer"` and `require "sidekiq/extensions/active_record"` in `lib/sidekiq/testing.rb`.
I referred to https://github.com/mperham/sidekiq/commit/2c5ab340c741417ff1500ef88d380ad5dab9cb1f.

### PR DESCRIPTION
**Pull request by fatkodima**
Closes #4300

### CODE REVIEW

**Comment by mperham** [comment]
Not the right solution. Put the test extension in the delay files.

**Comment by fatkodima** [comment]
Did you mean?
```ruby
# lib/extensions/action_mailer.rb
class DelayedMailer
  extend TestingExtensions
  include Sidekiq::Worker
  ...
end
```

If yes, isn't this testing related code will pollute those classes?

**Comment by mperham** [comment]
Or use if defined?  Requiring testing should not pull in the delayed feature implicitly.

**Comment by mperham** [comment]
Delayed are optional.  Testing is optional.  How do you pull in something which is optionally optional? 😄  The only issue now is that this:

```ruby
Sidekiq::Extensions.enable_delay!
require 'sidekiq/testing'
```

is different from:

```ruby
require 'sidekiq/testing'
Sidekiq::Extensions.enable_delay!
```

Understand?  I don't have a solution except to put the `extend if defined?` in **both** places.

**Pull request merged**
