### PR TITLE
shutdown all upstart instances on 'stop workers'

### PR DESCRIPTION
**Pull request by mpugach**

### CODE REVIEW

**Comment by seuros** [comment]
Thanks

**Comment by mpugach** [comment]
that was fast )

**Comment by seuros** [comment]
It was a performed async merge.

**Comment by mperham** [comment]
There's a reason we didn't do this. Check history

**Comment by mpugach** [comment]
Quick search gives me #2377 but it's not quite related. Files are different. Can you point me with link?

**Comment by mperham** [comment]
I was thinking #2401; this change looks ok.

**Comment by JamesChevalier** [comment]
Thanks for your work on this - I can't wait to use it!

I have a quick question, though... How do you `quiet` the sidekiq instances if you have `env NUM_WORKERS=2` in the `workers.conf` file? (My interest is specifically from within capistrano, but that detail might not be important.)

I found [this documentation](https://github.com/mperham/sidekiq/wiki/Deploying-to-Ubuntu#using-capistrano) that suggests this should work from within capistrano:

    puts capture("kill -USR1 $(sudo initctl status workers | grep /running | awk '{print $NF}') || :") 

I was trying it out manually, first, and I found that `sudo initctl status workers | grep /running | awk '{print $NF}'` would not print out PIDs, it would simply print out 'start/running'.

I can use `stop workers` instead, but that seems dangerous. I think the suggested practice is to send the `USR1` signal as early in the deploy as possible, and the restart as close to the end as possible.

**Comment by mperham** [comment]
`killall -USR1 sidekiq`?

**Comment by JamesChevalier** [comment]
`killall -USR1 sidekiq` doesn't work:
`sidekiq: no process found`

My guess is that it's because the processes have different names:

>$ ps aux | grep sidekiq
>... sidekiq 3.4.1 production [0 of 25 busy]
>... sidekiq 3.4.1 production [0 of 25 busy]

Based on some googling, it looks like this might work:
`pgrep -f 'sidekiq' | xargs kill -USR1`

**Pull request merged**
