### PR TITLE
Fix Rack::File deprecation

### LINKED ISSUE #4423: Rack::File deprecation warning
Ruby version: 2.6.3
Sidekiq version(s):  6.0.4

### Issue

Warning displayed:
`Rack::File is deprecated, please use Rack::Files instead.`

### Reproduction code

```ruby
require 'sidekiq/web'
puts "ok"
```

### Output

```
$ ruby test.rb
Rack::File is deprecated, please use Rack::Files instead.
ok
```

### Additional info

- The warning was introduced in Rack 2.1.0 - ref: https://github.com/rack/rack/blob/2.1.0/lib/rack/file.rb

### PR DESCRIPTION
**Pull request by DannyBen**
Closes #4423

### CODE REVIEW

**Comment by mperham** [comment]
I noted that Rack master has already reverted this deprecation.

**Comment by DannyBen** [comment]
They just removed the warning. `File` is an alias to `Files` since 2012.
https://github.com/rack/rack/pull/305

Should be changed, unless there are evidence that state that `Rack::File` is superior and preferred over `Rack::Files` - I did not find any.

**Comment by mperham** [comment]
I reverted this as it breaks Rack <2.0.8.

**Comment by mperham** [comment]
I would be happy to bump to Rack 2.1+ in Sidekiq 6.1 but I don't want to do it in master for a few weeks until this Rack mess stabilizes.

**Comment by DannyBen** [comment]
Alright, fair enough.

**Pull request merged**
