### PR TITLE
Sort keys in locales in alphabetical order

### PR DESCRIPTION
**Pull request by davetoxa**
I decide to check Russian locale on errors and missing keys and realized that its pretty hard to compare two files then keys have a random sort

This PR had sorted all keys for all locales for more convinient and faster translating

### CODE REVIEW

**Comment by mperham** [comment]
I add new strings to the end of en.yml.  You can see missing strings in each locale by looking at the end of each file.  I think this is much easier than scanning each file alphabetically, wdyt?

**Comment by davetoxa** [comment]
For example [last commit](https://github.com/mperham/sidekiq/commit/63be43f5e173ac73f865b2420ca30cbc4e00c95c) - locales were inserted in the middle of file :smiley:

**Comment by mperham** [comment]
Ah, not my commit.  Could you add a comment to the top of each file to add strings only at the bottom of each file?

**Comment by seuros** [comment]
I added it in the middle to match the other files.

**Comment by davetoxa** [comment]
@mperham additional `a comment to the top of each file` + my commit?

**Comment by seuros** [comment]
Without sorting them.

**Comment by mperham** [comment]
No sorting.  New keys go at the bottom.

**Pull request closed without merging**
