### PR TITLE
Add weights and version to queues on sidekiqmon and Sidekiq UI

### LINKED ISSUE #5640: Sidekiq weight on Sidekiq UI
Ruby version: 2.7.6p219
Rails version: 6.0.3.2
Sidekiq / Pro / Enterprise version(s): Sidekiq 6.4.2 / Pro 5.3.0 / Ent 2.3.0

Hi there!

Would be nice to see the weights on UI to make sure it is being defined as expected.

Here's how it looks right now:

Screen Shot 2022-11-17 at 13 27 31

Here's how it could look:

Screen Shot 2022-11-17 at 13 27 59

What do you think?

### PR DESCRIPTION
**Pull request by sobrinho**
It is backwards compatible in a way that sidekiqmon and Sidekiq UI will work during rolling deployments.

You can have one process in the previous version and another one in the new version and sidekiqmon/Sidekiq UI will work on both versions (legacy and new).

Before:

```
$ bundle exec sidekiqmon
Sidekiq 6.4.2
2022-11-17 18:28:14 UTC

---- Overview ----
  Processed: 0
     Failed: 0
       Busy: 0
   Enqueued: 0
    Retries: 0
  Scheduled: 0
       Dead: 0

---- Processes (2) ----
Gabriels-MacBook-Pro.local:60533:888acdb733ff []
  Started: 2022-11-17 15:16:46 -0300 (11 minutes ago)
  Threads: 2 (0 busy)
   Queues: critical, default, low

Gabriels-MacBook-Pro.local:62268:20c6394c86a7 []
  Started: 2022-11-17 15:25:21 -0300 (2 minutes ago)
  Threads: 50 (0 busy)
   Queues: critical, default, low

---- Queues (0) ----
NAME    SIZE  LATENCY
```

After:

```
$ bundle exec sidekiqmon
Sidekiq 7.0.1
2022-11-17 18:25:23 UTC

---- Overview ----
2022-11-17T18:25:23.251Z pid=62277 tid=1d5h INFO: Sidekiq 7.0.1 connecting to Redis with options {:size=>5, :pool_name=>"internal", :url=>nil}
  Processed: 0
     Failed: 0
       Busy: 0
   Enqueued: 0
    Retries: 0
  Scheduled: 0
       Dead: 0

---- Processes (2) ----
Gabriels-MacBook-Pro.local:60533:888acdb733ff []
  Started: 2022-11-17 15:16:46 -0300 (8 minutes ago)
  Threads: 2 (0 busy)
   Queues: critical, default, low
  Version: Unknown

Gabriels-MacBook-Pro.local:62268:20c6394c86a7 []
  Started: 2022-11-17 15:25:21 -0300 (just now)
  Threads: 50 (0 busy)
   Queues: critical: 100, default: 10, low: 1
  Version: 7.0.1

---- Queues (0) ----
NAME    SIZE  LATENCY
```

Before:

Screen Shot 2022-11-17 at 15 43 48

After:

Screen Shot 2022-11-17 at 15 36 03

Closes #5640

### CODE REVIEW

**Comment by sobrinho** [comment]
@mperham I also added the process version so we know that the weights aren't there because of the previous version.

**Comment by sobrinho** [comment]
Be aware that legacy processes won't have the weight and neither the default weight because we can't be sure all queues have the same weight.

That's why processes with the legacy data doesn't try to add it to the queue info.

**Comment by mperham** [comment]
I'm not sure `Version` needs its own line. How about hiding it IF the version == Sidekiq::VERSION or the version is unknown. We would only show the version if the process version is not equal to the Web UI's Sidekiq version (i.e. to highlight "this is an old process with a different version").

**Comment by sobrinho** [comment]
Sounds fair, let me adjust.

**Comment by sobrinho** [comment]
@mperham done!

**Comment by sobrinho** [comment]
@mperham not sure why the build broke, can you check?

It's working locally, doesn't seem related to the changes here.

**Comment by sobrinho** [comment]
Screen Shot 2022-11-17 at 16 44 32

**Comment by mperham** [comment]
Seems to be a ton of these errors. Looks like maybe a flaky test corrupted the suite?

```
Error:
Sidekiq::Testing.fake#test_0005_execute only jobs with assigned JID:
NoMethodError: undefined method `new' for #<Object:0x000055b091713f08>
    lib/sidekiq/middleware/chain.rb:198:in `make_new'
    lib/sidekiq/middleware/chain.rb:85:in `each'
    lib/sidekiq/middleware/chain.rb:85:in `each'
    lib/sidekiq/middleware/chain.rb:160:in `map'
    lib/sidekiq/middleware/chain.rb:160:in `retrieve'
    lib/sidekiq/middleware/chain.rb:172:in `invoke'
    lib/sidekiq/client.rb:87:in `push'
    lib/sidekiq/job.rb:365:in `client_push'
    lib/sidekiq/job.rb:198:in `perform_async'
    lib/sidekiq/job.rb:290:in `perform_async'
    test/testing_fake_test.rb:131:in `block (3 levels) in <top (required)>'
    test/testing_fake_test.rb:130:in `times'
    test/testing_fake_test.rb:130:in `block (2 levels) in <top (required)>'
```

**Pull request merged**
