### PR TITLE
Travis jruby update

### PR DESCRIPTION
**Pull request by PragTob**
Removed jruby-19mode as this is kind of the default now and added testing with jruby-head (that may fail) to help JRuby get prepped for an awesome 9k release :)

### CODE REVIEW

**Comment by seuros** [comment]
We still need to test jruby 1.9 until version sidekiq 4.x

**Comment by PragTob** [comment]
@seuros jruby-19 refers to the current jruby used in 1.9 mode. 1.9 is the default since jruby 1.7. Both jruby and jruby-19mode refer to jruby 1.7.19 so I don't think it's necessary.

**Comment by seuros** [comment]
Thanks you for your contribution.

**Comment by PragTob** [comment]
Thanks for your work on coderwall and state_machine gem among other things ;) :)

**Pull request merged**
