### PR TITLE
render a "cursor" that follows the tooltip

### PR DESCRIPTION
**Pull request by adamlogic**
This is not yet working.

The intention is to have a vertical line on the chart corresponding to the currently shown "tooltip" info in the legend below the chart. This is the behavior of Sidekiq 6.

### CODE REVIEW

**Comment by adamlogic** [comment]
I wanted to post my work here, but I'm ready to throw in the towel. The [chartjs-annotation-plugin](https://www.chartjs.org/chartjs-plugin-annotation/master/) isn't great to work with, and I can't figure out how to update the position of the vertical line as the tooltip updates.

If anybody wants to try to pick this up and get it working, have at it.

**Comment by mperham** [comment]
Would it be useful or reasonable to contact the maintainers and ask their advice? Maybe it’s a feature they would be interested in supporting.

**Comment by adamlogic** [comment]
Just needed to sleep on it, apparently. It's helpful to actually _include_ the chartjs-plugin-annotation library on the dashboard page. 🙄 

Anyway, this is working now. Here's a demo.


https://user-images.githubusercontent.com/372/190903872-347339a4-ed2d-4fec-9787-6a5dd789a3e6.mp4

**Comment by mperham** [comment]
Looks pretty good to me. I wonder if the bottom legend should be right aligned because the cursor will usually be on the right side of the graph. Otherwise your eyes jump from the right side cursor to the left side text. Confirm/deny?

**Comment by adamlogic** [comment]
I think you're right. It feels much more natural to have the legend under the right side of the chart.

CleanShot 2022-09-20 at 12 00 17

Note that I also moved the time to the right of the metrics so that it doesn't jump around as the cursor moves. Here's the "jumping" before I made that change:

CleanShot 2022-09-20 at 11 58 26

**Comment by mperham** [comment]
The values are still jumping and quite distracting. It’d be nice to use min-width or similar to minimize jumping. On Sep 20, 2022, at 09:05, Adam McCrea ***@***.***> wrote:﻿
I think you're right. It feels much more natural to have the legend under the right side of the chart.

Note that I also moved the time to the right of the metrics so that it doesn't jump around as the cursor moves. Here's the "jumping" before I made that change:

**Comment by adamlogic** [comment]
Since the width of the actual content changes as the values change, I think we have to choose:

1. Items shifting as widths change.
2. Inconsistent margins between items.

I tried applying a min-width to the items in the legend, and the result is an inconsistent margin that IMO looks worse than the jumping. The demo below was a local experiment, and is not part of this PR.

https://user-images.githubusercontent.com/372/191807082-25173025-a474-4a04-bcf0-087d74e91a45.mp4

Open to more ideas, but I think I'd call it good enough to ship. 🤷‍♂️

**Comment by mperham** [comment]
That demo video ^^^^^ looks perfect. You don't like it?

**Comment by adamlogic** [comment]
I didn't love the uneven spacing between the elements of the legend, but I didn't feel strongly either way. I tweaked it a bit, and I'm happier with this:


https://user-images.githubusercontent.com/372/191820716-20e2a07e-1517-4e94-93a6-168a2872e749.mp4


I pushed that change to the PR.

**Pull request merged**
