### PR TITLE
Fix locale definition for testing locale

### LINKED ISSUE #2752: Non-deterministic build?
The build is passing and failing randomly.  Investigate.

### PR DESCRIPTION
**Pull request by davydovanton**
Fixed #2752
I found the bug. It was in locale defenition before running test. If you look to [`locale_files`](https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/web_helpers.rb#L20-L24) method you can find that `@@locale_files` variable cache after first method call. And in test you call this method, and after you update `settings.locales` value.

### CODE REVIEW

**Comment by davydovanton** [comment]
Now I think all tests will be passed
/cc @mperham

**Comment by mperham** [comment]
The tests are still order-dependent.  I'd prefer to see the tests explicitly add the locale and clear the cache inside the `it` block or in a `before` block.

**Comment by davydovanton** [comment]
No, the problem is not in the order of the tests, the problem is in trying to update the locale files on the fly.  Therefore I consider that we need to replace all initial code to the top of file.  
But if you want to update locale files in the fly - I can offer other way. We can change `locale_files` value in before clock.
What do you think?

**Comment by mperham** [comment]
I'd like any global state changes (like the list of locales) to be local to each test.  That means if a test adds a locale before the test, it should remove the locale after the test.  And any locale caching needs to be cleared too, like @@strings and @@locale_files.

**Comment by mperham** [comment]
BTW I'm happy to do this work if my requirements aren't clear to you.

**Comment by davydovanton** [comment]
no, I understood you. I'm working on this now.

**Comment by davydovanton** [comment]
@mperham I added `before` and `after` blocks and if it solution is good for you - I can squash commits before a merge.

**Comment by mperham** [comment]
I developed my own solution which isn't quite as low-level as yours.  Hope you don't mind. https://github.com/mperham/sidekiq/commit/f8baa8af37274cacd3ef0437e9cede5ad5ecbe0d

**Pull request closed without merging**
