### PR TITLE
Initial pass at dark mode support, courtesy of @silent-e

### PR DESCRIPTION
**Pull request by mperham**
See #4227 for more discussion.

### CODE REVIEW

**Comment by fatkodima** [comment]
My full changed `application-dark.css`:
```css
@media (prefers-color-scheme: dark) {

  body {
    background-color: #111;
    color: #fff;
  }

  a,
  .title,
  .summary_bar ul .count,
  .navbar .navbar-brand {
    color: #af0014;
  }

  .navbar .navbar-brand:hover {
    color: #fff;
  }

  .navbar .navbar-brand .status {
    color: #fff;
  }

  table.table-white {
    background-color: #353535;
  }

  .table-striped > tbody > tr:nth-of-type(odd) {
    background-color: #212121;
  }

  .table-bordered,
  .table-bordered > tbody > tr > td,
  .table-bordered > tbody > tr > th,
  .table-bordered > tfoot > tr > td,
  .table-bordered > tfoot > tr > th,
  .table-bordered > thead > tr > td,
  .table-bordered > thead > tr > th {
    border: 1px solid #3d3d3d;
  }

  .table-hover > tbody > tr:hover {
    background-color: #232323;
  }

  .alert {
    border: none;
    color: #fff;
  }

  .alert-success {
    background-color: #000;
  }

  a:link,
  a:active,
  a:hover,
  a:visited {
    color: #63798c;
  }

  a.btn {
    color: #000;
  }

  .summary_bar .summary {
    background-color: #282828;
  }

  .navbar-default {
    background-color: #212121;
    border-color: #3d3d3d;
  }

  .navbar-default .navbar-nav > .active > a,
  .navbar-default .navbar-nav > .active > a:focus,
  .navbar-default .navbar-nav > .active > a:hover {
    color: #fff;
    background-color: #282828;
  }

  .navbar-default .navbar-nav > li > a:hover {
    color: #fff;
  }

  .pagination > li > a,
  .pagination > li > span {
    color: #fff;
    background-color: #282828;
    border-color: #353535;
  }
  .pagination > .disabled > a,
  .pagination > .disabled > a:focus,
  .pagination > .disabled > a:hover,
  .pagination > .disabled > span,
  .pagination > .disabled > span:focus,
  .pagination > .disabled > span:hover {
    color: #a5a5a5;
    background-color: #282828;
    border-color: #353535;
  }

  .stat {
    border: 1px solid rgba(255, 255, 255, 0.1);
  }

  #live-poll {
    color: #fff;
  }

  .btn-warn {
    color: #333;
  }

  .rickshaw_graph .y_ticks.glow text {
    fill: #fff;
    color: #fff;
  }
}
```

I'm terrible at design (color arrangements and the like), so I have not altered initial design (which btw already looks pretty neat), only fixed styling issues in a bunch of places.

**Comment by mperham** [comment]
Screen Shot 2019-09-27 at 9 56 20 AM

**Comment by rlt** [comment]
Is there a way to turn this mode off without changing my OS settings?

**Comment by mperham** [comment]
@rlt Nope.

**Comment by StanBright** [comment]
@rlt have you worked out a custom way to disable the dark mode? I definitely prefer the older version.

**Comment by hirowatari** [comment]
It would be nice to enable this without changing OS settings.  Looks cool.

**Comment by macmartine** [comment]
Is there really no way to turn off this dark mode?

**Pull request merged**
