### PR TITLE
Load stats with pipeline

### PR DESCRIPTION
**Pull request by ismaelga**
My attempt to load the stats in pipeline. This was the simplest way I could think of.

Comment are welcome :smile:

### CODE REVIEW

**Comment by mperham** [comment]
I'd write it simpler: load all metrics when Stats is initialized.  Include the process and worker counts too.

**Comment by ismaelga** [comment]
I'm not sure that's a good idea. Sometimes you just want one or two stats so loading everything on initialisation does not seem a good approach.

Take this for example https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/web.rb#L234 (actually might be the only one :confused: )

About the process and worker counts I totally agree.

**Comment by mperham** [comment]
This is true but the dominant cost is the network roundtrip and Stats is heavily used by the Web UI where it accesses most of the values on every page load.

**Comment by ismaelga** [comment]
Maybe it could be optional? `Stats.new(true)` where true would mean load all. Or the other way around.

**Comment by mperham** [comment]
I'm not clear what you are trying to optimize with the additional complexity.  Are you trying to minimize Redis operations?  I'd much rather avoid network round-trips and not make the developer worry about which mode they want to use.

**Comment by jonhyman** [comment]
Fwiw I agree with @mperham here. Optimizing the network roundtrips is much
more important, especially for these calls which are really fast on Redis.

**Comment by ismaelga** [comment]
Yes. I was trying to avoid extra operations on redis if someone just wanted to do `Stats.new.processed`.

To avoid roundtrips at all cost would you rather fit workers_size into this pipeline instead of using `Workers.new.size` for example?

**Comment by mperham** [comment]
Exactly.

**Comment by ismaelga** [comment]
Alright! Now I got it :sweat_smile:

**Comment by ismaelga** [comment]
This should pretty close to what you said. It now only uses 2 pipelines + redis_stats. Should that also go into one pipeline?

I'm still figuring out why one test is not passing.

**Comment by ismaelga** [comment]
Did a dummy benchmark by loading the data for /stats 1000 times: 1.527251s vs 5.147929s
:sunglasses:

**Comment by ismaelga** [comment]
Did some dummy benchmarks:
```
before
/stats  0.790000   0.190000   0.980000 (  1.149291)
summary 0.480000   0.120000   0.600000 (  0.689375)

after
/stats   0.340000   0.060000   0.400000 (  0.440624)
summary  0.280000   0.060000   0.340000 (  0.377405)
```
:sunglasses:

**Comment by mperham** [comment]
Fantastic work, @ismaelga!  3x improvement!!

**Comment by ismaelga** [comment]
Actually the difference should be even bigger when redis and sidekiq are not running on the same machine. :)

I just forgot to add it to the Changelog. You do that?

**Comment by davetoxa** [comment]
So, now it has a small transformation, of getting list of queues, is it? @ismaelga
`Sidekiq::Stats.new.queues` -> `Sidekiq::Stats::Queues.new.lengths`

**Comment by mperham** [comment]
@davetoxa ^^^

**Comment by davetoxa** [comment]
@mperham :smiley: :+1:

**Pull request merged**
