### PR TITLE
Using percentage sizes for footer information with ellipses overflow.

### PR DESCRIPTION
**Pull request by jcavalieri**
Also added title attributes so on-hover shows full string.

### CODE REVIEW

**Comment by mperham** [comment]
I pushed this into Sidekiq 3 also, although I'm not sure I should have.

**Comment by jcavalieri** [comment]
:-)

**Comment by mperham** [comment]
I reverted this as it looked bad with the stock Pro / Enterprise setup.

screen shot 2015-11-06 at 09 03 50

**Comment by mperham** [comment]
What do you think about this instead?

screen shot 2015-11-06 at 09 15 20

**Comment by jcavalieri** [comment]
That looks good. I think the .preX added more than I was expecting.

**Comment by jcavalieri** [comment]
My only concern might be when namespace is added.

**Comment by mperham** [comment]
Yeah, obvious that version string is about as long as its ever going to get.

**Comment by jcavalieri** [comment]
I calculated the percentages with some trial and error. It looked to me as long as the width percentages added up to 90% it seemed to not wrap.

**Comment by jcavalieri** [comment]
22.5
+22.5
+27
+18
=90

so more or less can be given to each one, as all four add up to 90

**Comment by jcavalieri** [comment]
Let me know if you want me to play around with it. I can mock it up on my local with the long '.preX' string.

**Comment by mperham** [comment]
I'm happy with it as is now.  Let me know how it works for you if you have the time to try it out.  4.0+ only.

**Comment by jcavalieri** [comment]
Looks good to me.

A couple tweaks if you want.

https://github.com/mperham/sidekiq/pull/2647

**Comment by jcavalieri** [comment]
wait, one moment

**Comment by jcavalieri** [comment]
Ok, PR is ready. Realized I wasn't consistent with the naming. Also added a screen shot.

**Pull request merged**
