### PR TITLE
CSRF vulnerability in Web UI

### PR DESCRIPTION
**Pull request by mperham**
Form POSTs don't verify an authenticity token so it's possible to do bad stuff.  Fix incoming...

### CODE REVIEW

**Comment by mperham** [comment]
This will break any 3rd party Web UI extensions which try to process POSTs.  They will need to update their forms to include the same hidden token input.

**Comment by davydovanton** [comment]
wow, nice changes! :tada: 
But I have a one question: why `#tkn` instead `#security_token`? I think that this name is more clear.

**Comment by mperham** [comment]
No reason.  Actually I should have pulled the entire line out: `<%= csrf_tag %>`

**Comment by davydovanton** [comment]
okay, I understand, thanks :)

**Pull request merged**
