### PR TITLE
Test on Ruby 2.2.3, move 2.0.0 to top of list

### PR DESCRIPTION
**Pull request by maclover7**

### CODE REVIEW

**Comment by davydovanton** [comment]
I think that this is cosmetic changes :grin:
@mperham what do you think?

**Comment by seuros** [comment]
2.2 should select the latest version in the 2.2.x serie. I think there is a problem with @travisci

**Comment by aprescott** [comment]
@seuros that's my understanding too, about `2.2` testing the latest `2.2.x` release.

**Comment by maclover7** [comment]
Just checked Travis, and it turns out you are right - specifying 2.2 will have Travis pull the latest 2.2.x release. Will close out this PR.

**Pull request closed without merging**
