### PR TITLE
Revert "Add farsi language to locals file (#3379)"

### PR DESCRIPTION
**Pull request by jsantos17**
This reverts commit 116237fcd8dfb0adb9b28792836e055409ec4602.

### CODE REVIEW

**Comment by mperham** [comment]
It's pretty rude to revert someone else's work without explanation.

**Comment by jsantos17** [comment]
image

Sorry. Somehow deleted the explanation while posting the screenshot. Text is not in the right direction.

**Comment by mperham** [comment]
Agreed, but that's a bug.  I'd be interested in working with native speakers to make the Sidekiq UI RTL-friendly.

**Comment by mperham** [comment]
#3381

**Pull request closed without merging**
